sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - cd ./client
  - docker build -t complex/react-test -f Dockerfile.dev .
  - cd ..

script:
  - docker run complex/react-test npm run test -- --coverage --watchAll=false

after_success:
  - docker build -t bachelorprojectsoti/multi-client ./client
  - docker build -t bachelorprojectsoti/multi-nginx ./nginx
  - docker build -t bachelorprojectsoti/multi-server ./server
  - docker build -t bachelorprojectsoti/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push bachelorprojectsoti/multi-client
  - docker push bachelorprojectsoti/multi-nginx
  - docker push bachelorprojectsoti/multi-server
  - docker push bachelorprojectsoti/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-044081138535
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
