version: '3'

services:
  postgres:
    image: 'postgres:11'

  redis:
    image: 'redis:5.0'
   
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      # REDIS_HOST = service aus docker-compose.yml
      - REDIS_HOST=redis
      # default port for redis
      - REDIS_PORT=6379
      # default user for postgres
      - PGUSER=postgres
      # default host for postgres
      - PGHOST=postgres
      # default database of postgres
      - PGDATABASE=postgres
      # defaul password of postgres
      - PGPASSWORD=postgres_password
      # default port of postgres
      - PGPORT=5432
    depends_on:
      - postgres
  
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

# Nginx Webserver connects req with /api/values/.... to React Server
# and req with /values/... to Express Server
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
